/**
 * The §2.21 catalogue, as data.
 *
 * STALE: extracted from the withdrawn §2.21 catalogue — all 269 scenarios across
 * 18 groups. It exists so that a scenario nobody has written is *visible*
 * rather than implied: `scenarios.spec.ts` turns every entry into a
 * `test.todo`, so the runner prints the real number outstanding instead of
 * reporting a green suite that covers nothing.
 *
 * When a scenario is written, delete its entry here and the todo goes with it.
 * The count in this file plus the count of real specs should always be 269.
 */

export type Scenario = {
  readonly n: number;
  readonly group: string;
  readonly holds: string;
  readonly text: string;
};

export const UNWRITTEN_SCENARIOS: readonly Scenario[] = [
  // --- A — Onboarding and activation ------------------------------------
  {
    n: 1,
    group: "A",
    holds: "F1.1, F1.3, F1.6",
    text: "Free-form intake enriches name, address, phone, hours, timezone and website in one request",
  },
  {
    n: 2,
    group: "A",
    holds: "F1.3",
    text: "An ambiguous business name offers a candidate list",
  },
  {
    n: 3,
    group: "A",
    holds: "F1.4",
    text: "Services are auto-extracted from the website, capped at five",
  },
  {
    n: 4,
    group: "A",
    holds: "F1.4, N7",
    text: "An unreachable website falls back to manual entry",
  },
  {
    n: 5,
    group: "A",
    holds: "F1.5",
    text: "Every enriched field is editable before commit",
  },
  {
    n: 6,
    group: "A",
    holds: "F1.7c",
    text: "The consent screen names each scope and its reason before Google opens",
  },
  {
    n: 7,
    group: "A",
    holds: "F1.7",
    text: "Signing in with calendar granted stores an offline token",
  },
  {
    n: 8,
    group: "A",
    holds: "F1.7a, F1.7b",
    text: "Calendar declined: sign-in completes, the draft survives, onboarding stops at the explainer",
  },
  {
    n: 9,
    group: "A",
    holds: "F1.7b",
    text: "A declined-calendar account sits unbilled under the 10-day clock and is never charged",
  },
  {
    n: 10,
    group: "A",
    holds: "F1.9",
    text: "The number is bought and the agent bound behind the value screen",
  },
  {
    n: 11,
    group: "A",
    holds: "F1.12a-ii",
    text: "The bind is verified by reading provider state back",
  },
  {
    n: 12,
    group: "A",
    holds: "F1.12a-ii, F9.6",
    text: "A failed bind verification is retried and raised to the operator",
  },
  {
    n: 13,
    group: "A",
    holds: "F1.11",
    text: "The contact email defaults from the Google identity and is editable",
  },
  {
    n: 14,
    group: "A",
    holds: "F1.11, F1.12",
    text: "An unverified contact email blocks activation",
  },
  {
    n: 15,
    group: "A",
    holds: "F1.12",
    text: "The checklist shows three tasks in any order, plus test calls remaining",
  },
  {
    n: 16,
    group: "A",
    holds: "F1.12a",
    text: "Activate is unavailable until all three items are green",
  },
  {
    n: 17,
    group: "A",
    holds: "F1.12a",
    text: "Pressing Activate charges $100, opens period 1, and says the number is now taking calls",
  },
  {
    n: 18,
    group: "A",
    holds: "F1.12b",
    text: "Confirming the test call alone neither activates nor charges",
  },
  {
    n: 19,
    group: "A",
    holds: "F1.12b",
    text: "Adding a card alone neither activates nor charges",
  },
  {
    n: 20,
    group: "A",
    holds: "F1.12b",
    text: "Time passing never activates a business",
  },
  {
    n: 21,
    group: "A",
    holds: "F1.12a-i",
    text: "A card declined at activation changes nothing and charges nothing",
  },
  {
    n: 22,
    group: "A",
    holds: "F1.12a-i",
    text: "A local write failing after the charge is completed by Ringly, never re-prompted",
  },
  {
    n: 23,
    group: "A",
    holds: "F1.12a-i",
    text: "A bind failing at activation still confirms the charge and emails when the number is live",
  },
  {
    n: 24,
    group: "A",
    holds: "§2.4a.1",
    text: "Pressing Activate twice cannot charge twice",
  },
  // --- B — Test-call allowance ------------------------------------------
  {
    n: 25,
    group: "B",
    holds: "F1.13c",
    text: "Calls before activation are recorded as test calls and never billed",
  },
  {
    n: 26,
    group: "B",
    holds: "F1.13c",
    text: "A stranger's call still counts against the allowance",
  },
  {
    n: 27,
    group: "B",
    holds: "F1.13a",
    text: "The fifth test call unbinds the agent",
  },
  {
    n: 28,
    group: "B",
    holds: "F1.13a",
    text: "The sixth call is not answered at all — no connected minutes are consumed",
  },
  {
    n: 29,
    group: "B",
    holds: "F1.13a",
    text: "The business is emailed on exhaustion, in every case",
  },
  {
    n: 30,
    group: "B",
    holds: "F1.13a",
    text: "The operator is alerted only when the test call was never confirmed",
  },
  {
    n: 31,
    group: "B",
    holds: "F1.13a",
    text: "A business with all three items green that exhausts is emailed but not escalated",
  },
  {
    n: 32,
    group: "B",
    holds: "F1.13b",
    text: "An exhausted business can still activate, and that rebinds the number",
  },
  {
    n: 33,
    group: "B",
    holds: "F1.13b",
    text: "A business that never confirmed a working call cannot activate",
  },
  {
    n: 34,
    group: "B",
    holds: "F10.1c",
    text: "An operator reset restores the allowance and rebinds the agent together",
  },
  {
    n: 35,
    group: "B",
    holds: "F1.13",
    text: "Changing the allowance configuration changes the limit without a deploy",
  },
  {
    n: 36,
    group: "B",
    holds: "F1.13c",
    text: "Activating does not reclassify a business's earlier test calls",
  },
  {
    n: 37,
    group: "B",
    holds: "F1.13c, F7.7",
    text: "After activation the owner's own call is billed like any other",
  },
  // --- C — Call handling and booking ------------------------------------
  {
    n: 38,
    group: "C",
    holds: "F2.1",
    text: "The agent identifies the business and describes services, prices and durations",
  },
  {
    n: 39,
    group: "C",
    holds: "F2.1a",
    text: "The recording disclosure is spoken on every call",
  },
  {
    n: 40,
    group: "C",
    holds: "F2.1a",
    text: "A business cannot remove or alter the disclosure through its greeting",
  },
  {
    n: 41,
    group: "C",
    holds: "F2.1a",
    text: "With no custom greeting, the default disclosure text is used verbatim",
  },
  {
    n: 42,
    group: "C",
    holds: "F2.2",
    text: "Booking a free slot succeeds and the event appears in the connected calendar",
  },
  {
    n: 43,
    group: "C",
    holds: "F2.3",
    text: "A slot conflicting with an existing Ringly appointment is refused with alternatives",
  },
  {
    n: 44,
    group: "C",
    holds: "F2.3",
    text: "A slot conflicting with an externally-created calendar event is refused",
  },
  {
    n: 45,
    group: "C",
    holds: "F2.3a",
    text: "Two callers racing one slot: the second is refused and exactly one appointment exists",
  },
  {
    n: 46,
    group: "C",
    holds: "F2.4",
    text: "A reschedule on full name, date, time and service match succeeds",
  },
  {
    n: 47,
    group: "C",
    holds: "F2.4",
    text: "A partial match is refused and the caller is told what did not match",
  },
  {
    n: 48,
    group: "C",
    holds: "F2.4",
    text: "A corrected detail re-runs the search",
  },
  {
    n: 49,
    group: "C",
    holds: "F2.4",
    text: "A caller ringing from a different number can still reschedule",
  },
  {
    n: 50,
    group: "C",
    holds: "F2.4",
    text: "One person calling from two numbers becomes two customer records",
  },
  {
    n: 51,
    group: "C",
    holds: "F2.4",
    text: "A relative day resolves to the next such day and is read back for confirmation",
  },
  {
    n: 52,
    group: "C",
    holds: "F2.4",
    text: "An occurrence of a series triggers the this-one-or-all question",
  },
  {
    n: 53,
    group: "C",
    holds: "F2.4",
    text: "A one-off appointment does not trigger that question",
  },
  {
    n: 54,
    group: "C",
    holds: "F2.5",
    text: "Every time spoken to a caller is in the business's timezone",
  },
  {
    n: 55,
    group: "C",
    holds: "F2.6",
    text: "Filler speech covers backend waits",
  },
  {
    n: 56,
    group: "C",
    holds: "F2.8",
    text: "The agent answers at 3am but refuses to book outside opening hours",
  },
  {
    n: 57,
    group: "C",
    holds: "F2.9",
    text: "A booking beyond the horizon is refused",
  },
  {
    n: 58,
    group: "C",
    holds: "F2.9",
    text: "A changed booking horizon applies to the next caller",
  },
  {
    n: 59,
    group: "C",
    holds: "F2.9",
    text: "A horizon outside 7–180 days is rejected",
  },
  {
    n: 60,
    group: "C",
    holds: "F2.10",
    text: "The agent cannot transfer, says so, gives the business's own details, and records dropped",
  },
  {
    n: 61,
    group: "C",
    holds: "F2.11",
    text: "The confirmation is the read-back alone; no message is ever promised",
  },
  {
    n: 62,
    group: "C",
    holds: "F2.2",
    text: "Cancelling a real appointment removes the calendar event",
  },
  // --- D — Fail-closed calendar -----------------------------------------
  {
    n: 63,
    group: "D",
    holds: "F2.7",
    text: "A calendar that cannot be reached writes no appointment and the caller is apologised to",
  },
  {
    n: 64,
    group: "D",
    holds: "N3.1",
    text: 'A calendar timeout is treated as failure, never as "no conflicts"',
  },
  {
    n: 65,
    group: "D",
    holds: "F2.7a",
    text: "Revoked consent refuses booking and surfaces reconnect on the dashboard",
  },
  {
    n: 66,
    group: "D",
    holds: "F2.7, §2.8a",
    text: "An outage raises the dashboard banner above the filters",
  },
  {
    n: 67,
    group: "D",
    holds: "F2.7",
    text: "An outage sends one email per incident, not one per failed call",
  },
  {
    n: 68,
    group: "D",
    holds: "F2.7",
    text: "The warning clears itself on the first successful calendar read",
  },
  {
    n: 69,
    group: "D",
    holds: "F4.5",
    text: "Enquiries still work during an outage; only booking stops",
  },
  {
    n: 70,
    group: "D",
    holds: "F9.12",
    text: 'The operator dashboard shows the business under "bookings failing"',
  },
  // --- E — Catalogue and opening hours ----------------------------------
  {
    n: 71,
    group: "E",
    holds: "F3.1",
    text: "Services can be added, edited, deactivated and reordered",
  },
  {
    n: 72,
    group: "E",
    holds: "F3.2",
    text: "A catalogue change reaches the next caller within 60 seconds",
  },
  {
    n: 73,
    group: "E",
    holds: "F3.2",
    text: "A caller mid-conversation keeps the catalogue they started with",
  },
  {
    n: 74,
    group: "E",
    holds: "F3.3",
    text: "Deactivating a service leaves appointments already booked against it untouched",
  },
  {
    n: 75,
    group: "E",
    holds: "F3.4",
    text: "Price resolves at the time of the appointment, not the time of booking",
  },
  {
    n: 76,
    group: "E",
    holds: "F3.4",
    text: "Duration is locked at booking and repricing never moves neighbouring appointments",
  },
  {
    n: 77,
    group: "E",
    holds: "F3.4",
    text: "A deleted service values its appointments at the last known price",
  },
  {
    n: 78,
    group: "E",
    holds: "F3.5",
    text: "Hours edited on the dashboard reach the next caller",
  },
  {
    n: 79,
    group: "E",
    holds: "F3.5",
    text: "Narrowing hours never moves or cancels an existing appointment",
  },
  {
    n: 80,
    group: "E",
    holds: "F3.5",
    text: "Widening hours makes the new slots bookable immediately",
  },
  {
    n: 81,
    group: "E",
    holds: "F3.6",
    text: "A business cannot change its own timezone",
  },
  // --- F — Recurring appointments ---------------------------------------
  {
    n: 82,
    group: "F",
    holds: "F5.1",
    text: "A caller sets up a recurring series in one call",
  },
  {
    n: 83,
    group: "F",
    holds: "F5.2",
    text: "Occurrences are materialised out to the horizon",
  },
  {
    n: 84,
    group: "F",
    holds: "F5.2, §2.7",
    text: "A materialisation horizon below the booking horizon is rejected",
  },
  {
    n: 85,
    group: "F",
    holds: "F5.2a",
    text: "An occurrence landing on a taken slot shifts within ±2 hours the same day",
  },
  {
    n: 86,
    group: "F",
    holds: "F5.2a",
    text: "An occurrence with nothing free in that window is skipped, not moved to another day",
  },
  {
    n: 87,
    group: "F",
    holds: "F5.2b, F5.2c",
    text: "A shift or skip emails the owner and states plainly that the customer was not told",
  },
  {
    n: 88,
    group: "F",
    holds: "§2.7",
    text: "Owner notifications are batched per run, not per occurrence",
  },
  {
    n: 89,
    group: "F",
    holds: "F5.2e",
    text: "An occurrence falling outside newly-narrowed hours is shifted or skipped",
  },
  {
    n: 90,
    group: "F",
    holds: "F5.2e",
    text: "Occurrences already generated are not swept up when hours change",
  },
  {
    n: 91,
    group: "F",
    holds: "F5.3",
    text: "Cancelling a series cancels future occurrences and leaves past ones intact",
  },
  {
    n: 92,
    group: "F",
    holds: "F5.2",
    text: "Cancelling one occurrence leaves the rest of the series intact",
  },
  {
    n: 93,
    group: "F",
    holds: "§2.7",
    text: "Re-running the materialiser creates no duplicate occurrences",
  },
  // --- G — Business dashboard -------------------------------------------
  {
    n: 94,
    group: "G",
    holds: "F6.1, N1.1",
    text: "A business sees only its own data",
  },
  {
    n: 95,
    group: "G",
    holds: "F6.2",
    text: "The unit and range filters govern every figure on the page",
  },
  { n: 96, group: "G", holds: "F6.3", text: "All six call metrics render" },
  {
    n: 97,
    group: "G",
    holds: "F6.3",
    text: '"Calls that booked" counts calls, not appointments',
  },
  {
    n: 98,
    group: "G",
    holds: "F6.3a",
    text: "Revenue booked is labelled an estimate when the range includes future appointments",
  },
  {
    n: 99,
    group: "G",
    holds: "F6.3b",
    text: "Time of day renders as six business-local four-hour windows",
  },
  {
    n: 100,
    group: "G",
    holds: "F6.3c",
    text: "Outcomes filter by time window and time-of-day filters by outcome",
  },
  {
    n: 101,
    group: "G",
    holds: "F6.3d",
    text: "Enquiry-only and dropped are counted separately",
  },
  {
    n: 102,
    group: "G",
    holds: "F6.3e",
    text: "Three separate trend charts render on a shared x-axis",
  },
  {
    n: 103,
    group: "G",
    holds: "F6.3f",
    text: "What the business pays Ringly is absent from the call metrics",
  },
  {
    n: 104,
    group: "G",
    holds: "F6.4",
    text: "Dropped covers hang-ups and cannot-helps; a completed enquiry is separate",
  },
  {
    n: 105,
    group: "G",
    holds: "F6.5",
    text: "Outcome definitions render from data, not from the component",
  },
  {
    n: 106,
    group: "G",
    holds: "F6.6",
    text: "A range spanning a definition change shows the notice and reclassifies nothing",
  },
  {
    n: 107,
    group: "G",
    holds: "F6.7, F6.8",
    text: "Billing history is one table with the current period as its first row",
  },
  {
    n: 108,
    group: "G",
    holds: "F6.7",
    text: "A period during which service was suspended is labelled in its row",
  },
  {
    n: 109,
    group: "G",
    holds: "F6.9",
    text: "No transcript, recording or per-customer figure is reachable",
  },
  {
    n: 110,
    group: "G",
    holds: "F6.10",
    text: "Externally-created calendar events never appear in the figures",
  },
  {
    n: 111,
    group: "G",
    holds: "F6.11",
    text: "Every figure renders in the business's own timezone",
  },
  {
    n: 112,
    group: "G",
    holds: "F6.12",
    text: "Dashboard queries return within budget regardless of tenant size",
  },
  {
    n: 113,
    group: "G",
    holds: "F6.13",
    text: "All seven dashboard controls are present",
  },
  {
    n: 114,
    group: "G",
    holds: "F6.14",
    text: "The freshness line states the complete-to date and that today appears tomorrow",
  },
  {
    n: 115,
    group: "G",
    holds: "F6.14",
    text: "Median and billing figures are labelled live; everything else is nightly",
  },
  {
    n: 116,
    group: "G",
    holds: "F6.14a",
    text: "Every money figure is labelled settled, accruing or outstanding",
  },
  {
    n: 117,
    group: "G",
    holds: "F6.15",
    text: "Service status shows whether the number is live, the number, and calls remaining",
  },
  {
    n: 118,
    group: "G",
    holds: "F6.15",
    text: "When the number is not live, the status says why and what turns it back on",
  },
  // --- H — Billing, the paying path -------------------------------------
  {
    n: 119,
    group: "H",
    holds: "F7.1",
    text: "$100 is charged on day 1 of every period",
  },
  {
    n: 120,
    group: "H",
    holds: "F7.2",
    text: "The card is stored for off-session use at activation",
  },
  {
    n: 121,
    group: "H",
    holds: "F7.3, N6.2",
    text: "Raw card details never reach Ringly",
  },
  {
    n: 122,
    group: "H",
    holds: "F7.5, F7.6",
    text: "Usage accrues only on productive calls",
  },
  {
    n: 123,
    group: "H",
    holds: "F7.6",
    text: "Enquiry, dropped and wrong-number calls accrue no usage",
  },
  {
    n: 124,
    group: "H",
    holds: "F7.7",
    text: "The whole call is billable, not only the minutes up to the booking",
  },
  {
    n: 125,
    group: "H",
    holds: "F7.7a",
    text: "Seconds are summed across the period and rounded up once",
  },
  {
    n: 126,
    group: "H",
    holds: "F7.8, F7.16",
    text: "A rate change applies without a deploy and leaves settled periods untouched",
  },
  {
    n: 127,
    group: "H",
    holds: "F7.4",
    text: "Usage settles on the period's last day",
  },
  {
    n: 128,
    group: "H",
    holds: "F7",
    text: "The next period opens the following day with its own $100",
  },
  {
    n: 129,
    group: "H",
    holds: "F7",
    text: "The fixed fee and the usage settlement never fall on the same day",
  },
  {
    n: 130,
    group: "H",
    holds: "F7.9",
    text: "Usage past the cap is recorded in full but charged short",
  },
  {
    n: 131,
    group: "H",
    holds: "F7.9b",
    text: "Crossing the cap emails the business and alerts the operator",
  },
  {
    n: 132,
    group: "H",
    holds: "F7.9b",
    text: "Service continues after the cap and the excess is absorbed",
  },
  {
    n: 133,
    group: "H",
    holds: "F7.12d",
    text: "$470 of usage results in $500 charged and $70 absorbed",
  },
  {
    n: 134,
    group: "H",
    holds: "F7.14",
    text: "Every charge, refund and failure is recorded immutably",
  },
  {
    n: 135,
    group: "H",
    holds: "F7.16",
    text: "A settled period is unchanged by a later pricing-policy change",
  },
  {
    n: 136,
    group: "H",
    holds: "F7.18",
    text: "Sales tax is stored as Stripe calculated it, never computed by Ringly",
  },
  // --- I — Failure, grace, suspension and recovery ----------------------
  {
    n: 137,
    group: "I",
    holds: "F7.11",
    text: "A declined fixed fee starts grace with service continuing",
  },
  {
    n: 138,
    group: "I",
    holds: "F7.11c-ii",
    text: "Grace usage is billable when a period is open to bill it to",
  },
  {
    n: 139,
    group: "I",
    holds: "F10.3",
    text: "Day 7 unpaid suspends the business, unbinds the agent and stops the number",
  },
  {
    n: 140,
    group: "I",
    holds: "F1.12a-ii",
    text: "A failed unbind is retried and raised to the operator",
  },
  {
    n: 141,
    group: "I",
    holds: "F7.11b, F7.11c",
    text: "Suspension adds no fixed fee, no usage and no new period",
  },
  {
    n: 142,
    group: "I",
    holds: "F7.11b",
    text: "Suspension does not extend the billing period",
  },
  {
    n: 143,
    group: "I",
    holds: "F7.11d",
    text: "A period ending mid-suspension settles on its original last day with no successor",
  },
  {
    n: 144,
    group: "I",
    holds: "F7.11c",
    text: "The debt is frozen through suspension — day 55 owes exactly what day 8 owed",
  },
  {
    n: 145,
    group: "I",
    holds: "F7.11d",
    text: "Case (a): paying on day 20 resumes inside the period with nothing new charged",
  },
  {
    n: 146,
    group: "I",
    holds: "F7.11d",
    text: "Case (a): the day-30 settlement covers days 1–8 and 20–30",
  },
  {
    n: 147,
    group: "I",
    holds: "F7.11d",
    text: "Case (a): paying on day 45 clears $100 plus usage, then opens a new period at $100",
  },
  {
    n: 148,
    group: "I",
    holds: "F7.11d",
    text: "Case (b): a declined settlement closes the period and opens no successor",
  },
  {
    n: 149,
    group: "I",
    holds: "F7.11c-ii",
    text: "Case (b): the grace days are served, not billed, and their cost is still recorded",
  },
  {
    n: 150,
    group: "I",
    holds: "F7.11d",
    text: "Case (b): paying on day 45 and on day 70 are identical transactions",
  },
  {
    n: 151,
    group: "I",
    holds: "F7.10b",
    text: "A partial payment leaves the business suspended and the email says what remains",
  },
  {
    n: 152,
    group: "I",
    holds: "F7.11b-i",
    text: "Stripe retries continue throughout suspension",
  },
  {
    n: 153,
    group: "I",
    holds: "F7.11b-ii",
    text: "Every payment email is Ringly's; Stripe's dunning stays silent",
  },
  {
    n: 154,
    group: "I",
    holds: "F10.3a",
    text: "The 48-hour deletion warning arrives before the deadline",
  },
  {
    n: 155,
    group: "I",
    holds: "F7.10b",
    text: "Payment clearing restores service the same day and emails the business",
  },
  {
    n: 156,
    group: "I",
    holds: "F7.11b-iii",
    text: "Restoring into a still-running period charges nothing extra",
  },
  {
    n: 157,
    group: "I",
    holds: "F7.11b-iii",
    text: "Restoring with no open period opens exactly one, at $100 that day",
  },
  {
    n: 158,
    group: "I",
    holds: "F7.11b-iii",
    text: "The debt clears before the new period's fee — two movements on the same day",
  },
  {
    n: 159,
    group: "I",
    holds: "F7.11b-iv",
    text: "A decline on the new period's fee starts a fresh grace and deletion clock",
  },
  {
    n: 160,
    group: "I",
    holds: "F7.10b-i",
    text: "A missed webhook is caught by the daily reconciliation",
  },
  {
    n: 161,
    group: "I",
    holds: "§2.9.5",
    text: "Reconciliation finding a stranded business raises an operator alert",
  },
  {
    n: 162,
    group: "I",
    holds: "§2.9.5",
    text: "A redelivered webhook cannot restore twice or open two periods",
  },
  {
    n: 163,
    group: "I",
    holds: "F7.17",
    text: "A chargeback follows the non-payment path exactly",
  },
  {
    n: 164,
    group: "I",
    holds: "§2.10",
    text: "The 60-day deletion clock is not paused by suspension",
  },
  {
    n: 165,
    group: "I",
    holds: "I3",
    text: "Debt never exceeds $500 exclusive of tax",
  },
  {
    n: 166,
    group: "I",
    holds: "F7c",
    text: "Case (a) can reach $500; case (b) can reach $400",
  },
  // --- J — Cancellation and dormancy ------------------------------------
  {
    n: 167,
    group: "J",
    holds: "F7.12",
    text: "Marking cancelled opens the window with service continuing and usage unbilled",
  },
  {
    n: 168,
    group: "J",
    holds: "F7.12",
    text: "The window is 7 days or period end, whichever comes first",
  },
  {
    n: 169,
    group: "J",
    holds: "F7.12",
    text: "Countdown emails run through the window",
  },
  {
    n: 170,
    group: "J",
    holds: "F7.12a",
    text: "Revoking makes the window's usage billable and restores the original end date",
  },
  {
    n: 171,
    group: "J",
    holds: "F7.12b",
    text: "The window closing settles the period early and refunds no part of the $100",
  },
  { n: 172, group: "J", holds: "F7.12c", text: "A closing statement is sent" },
  {
    n: 173,
    group: "J",
    holds: "F7.12e",
    text: "Dormancy retains the number and every record for 60 days",
  },
  {
    n: 174,
    group: "J",
    holds: "F7.12e",
    text: "Returning inside dormancy resumes the same number and history on a new period",
  },
  {
    n: 175,
    group: "J",
    holds: "F7.12e",
    text: "Returning after dormancy is a wholly new account with a new number",
  },
  {
    n: 176,
    group: "J",
    holds: "F7.12f",
    text: "A failed settlement charge is recorded as owed and never retried",
  },
  {
    n: 177,
    group: "J",
    holds: "F7.11a",
    text: "A business behind on payment cannot cancel into free service",
  },
  {
    n: 178,
    group: "J",
    holds: "F7.10",
    text: "A cancelled business is never charged again unless it withdraws",
  },
  {
    n: 179,
    group: "J",
    holds: "F7.10a, F9.10",
    text: "Only the operator can set or clear cancelled status",
  },
  // --- K — Lifecycle, numbers and deletion ------------------------------
  {
    n: 180,
    group: "K",
    holds: "F10.1",
    text: "A business that never activates is deleted at day 10 and its number released",
  },
  {
    n: 181,
    group: "K",
    holds: "F10.1b",
    text: "The operator can pause the 10-day clock",
  },
  {
    n: 182,
    group: "K",
    holds: "F10.1b",
    text: "Silence pauses nothing — the default stands",
  },
  {
    n: 183,
    group: "K",
    holds: "F9.6a",
    text: "The operator is alerted before day 10 even when the business is not stuck",
  },
  {
    n: 184,
    group: "K",
    holds: "F10.3a, I4",
    text: "Nothing is deleted without a 48-hour warning, on any path",
  },
  {
    n: 185,
    group: "K",
    holds: "F10.3c",
    text: "Deletion emails both the business and the operator, on every path",
  },
  {
    n: 186,
    group: "K",
    holds: "F10.3d",
    text: "The deletion email is sent before the address that receives it is destroyed",
  },
  {
    n: 187,
    group: "K",
    holds: "§2.9.4",
    text: "Teardown runs in order: capture, Stripe, number, emails, rows, record",
  },
  {
    n: 188,
    group: "K",
    holds: "F10.4b",
    text: "The number is handed back to the provider and not pooled",
  },
  {
    n: 189,
    group: "K",
    holds: "F10.4a",
    text: "A suspended business's number is never offered as reusable",
  },
  {
    n: 190,
    group: "K",
    holds: "F10.4a",
    text: "A dormant business's number is never offered as reusable",
  },
  {
    n: 191,
    group: "K",
    holds: "F10.4a",
    text: "An unactivated business that spent its allowance keeps its number reserved",
  },
  {
    n: 192,
    group: "K",
    holds: "F10.4a",
    text: "A deleted business's number leaves the pool",
  },
  {
    n: 193,
    group: "K",
    holds: "F10.9",
    text: "The departure record holds identity and money and no consumer data",
  },
  {
    n: 194,
    group: "K",
    holds: "F10.10",
    text: "The departure record is captured before teardown destroys its source",
  },
  {
    n: 195,
    group: "K",
    holds: "F10.5, R18",
    text: "The 10-day path issues an explicit provider-side content delete",
  },
  {
    n: 196,
    group: "K",
    holds: "F10.5",
    text: "The 60-day paths need no provider-side delete",
  },
  {
    n: 197,
    group: "K",
    holds: "F10.6",
    text: "Ringly never stores a transcript or a recording",
  },
  {
    n: 198,
    group: "K",
    holds: "F10.7",
    text: "Call content older than 30 days is not retrievable",
  },
  {
    n: 199,
    group: "K",
    holds: "F10.8",
    text: "Nothing is aged out while a business is active",
  },
  // --- L — Customer PII deletion ----------------------------------------
  {
    n: 200,
    group: "L",
    holds: "F10.1a-i",
    text: "The owner deletes a customer by phone number, immediately and without an operator",
  },
  {
    n: 201,
    group: "L",
    holds: "F10.1a-i",
    text: "The customer row and every piece of PII are erased",
  },
  {
    n: 202,
    group: "L",
    holds: "§2.10.2",
    text: "Their recurring series is cancelled and deleted",
  },
  {
    n: 203,
    group: "L",
    holds: "F10.1a-i",
    text: "Future appointments are deleted and their calendar events withdrawn",
  },
  {
    n: 204,
    group: "L",
    holds: "F10.1a-i",
    text: "Past appointments survive with the customer link removed",
  },
  {
    n: 205,
    group: "L",
    holds: "F10.1a-i",
    text: "Calls are untouched — they carry no link and no content",
  },
  {
    n: 206,
    group: "L",
    holds: "F7.16",
    text: "Settled billing figures are unchanged by the deletion",
  },
  {
    n: 207,
    group: "L",
    holds: "§2.8a",
    text: "The lookup never lists customers or resolves a number into a name",
  },
  {
    n: 208,
    group: "L",
    holds: "F10.1a-i",
    text: "The deletion warns that it is irreversible before confirming",
  },
  {
    n: 209,
    group: "L",
    holds: "F10.1a-ii",
    text: "Deleting the business destroys every customer's PII automatically",
  },
  // --- M — Email --------------------------------------------------------
  {
    n: 210,
    group: "M",
    holds: "F8.2",
    text: "Nothing outside the registry is ever sent",
  },
  {
    n: 211,
    group: "M",
    holds: "F8.4",
    text: "Transactional email cannot be unsubscribed from",
  },
  {
    n: 212,
    group: "M",
    holds: "F8.4",
    text: "The stats-digest opt-out is honoured",
  },
  {
    n: 213,
    group: "M",
    holds: "§2.12",
    text: "The dispatcher refuses to consult an opt-out for a transactional kind",
  },
  {
    n: 214,
    group: "M",
    holds: "F8.5",
    text: "Per-period idempotency sends the digest at most once per period",
  },
  {
    n: 215,
    group: "M",
    holds: "F8.5",
    text: "Per-incident idempotency sends one email for an outage however many calls it affects",
  },
  {
    n: 216,
    group: "M",
    holds: "F8.5",
    text: "Per-event idempotency sends one email per shifted occurrence",
  },
  {
    n: 217,
    group: "M",
    holds: "F8.5",
    text: "A retried worker never sends the same message twice",
  },
  {
    n: 218,
    group: "M",
    holds: "F8.11",
    text: "The four streams send from four separate identities",
  },
  {
    n: 219,
    group: "M",
    holds: "F8.3a",
    text: "Ringly never sends a receipt, an invoice or a payment-succeeded notice",
  },
  {
    n: 220,
    group: "M",
    holds: "F8.8",
    text: "Every email states what happened, what it means, and what happens next",
  },
  {
    n: 221,
    group: "M",
    holds: "F8.9",
    text: "Amounts carry currency and dates are absolute",
  },
  {
    n: 222,
    group: "M",
    holds: "F8.12",
    text: "Operator alerts lead with the business name and the money at stake",
  },
  {
    n: 223,
    group: "M",
    holds: "F8.13, F9.6",
    text: "The operator alert set is exactly the declared one and no more",
  },
  // --- N — Operator dashboard -------------------------------------------
  {
    n: 224,
    group: "N",
    holds: "F9.1",
    text: "An authenticated business owner receives 404 from every /ops route",
  },
  {
    n: 225,
    group: "N",
    holds: "§2.11",
    text: "No tenant-facing module imports the ops module, and none the other way",
  },
  {
    n: 226,
    group: "N",
    holds: "F9.2",
    text: "Range and business selector govern every figure on the page",
  },
  {
    n: 227,
    group: "N",
    holds: "F9.2a",
    text: "The money table sorts on every column",
  },
  {
    n: 228,
    group: "N",
    holds: "F9.2b",
    text: "The margin chart has a zero baseline and renders a negative month as negative",
  },
  {
    n: 229,
    group: "N",
    holds: "F9.2b",
    text: "The outcomes-by-time-of-day chart is present",
  },
  {
    n: 230,
    group: "N",
    holds: "F9.2c",
    text: "No per-business call, duration or outcome columns appear in the table",
  },
  {
    n: 231,
    group: "N",
    holds: "F9.2d",
    text: "No per-customer figure appears anywhere",
  },
  {
    n: 232,
    group: "N",
    holds: "F9.2e",
    text: "View-as-business is read-only, banner-marked, and creates no business session",
  },
  {
    n: 233,
    group: "N",
    holds: "F9.2e",
    text: "Every business control is absent from the borrowed view",
  },
  {
    n: 234,
    group: "N",
    holds: "F9.3",
    text: "Payment reliability is shown per business",
  },
  {
    n: 235,
    group: "N",
    holds: "F9.4",
    text: "Platform totals include the count of active businesses",
  },
  {
    n: 236,
    group: "N",
    holds: "F9.5",
    text: "The cost model attributes Retell and nothing else",
  },
  {
    n: 237,
    group: "N",
    holds: "F9.6",
    text: "Operator alerts are delivered by email",
  },
  {
    n: 238,
    group: "N",
    holds: "F9.8, F6.14a",
    text: "Figures are reported by calendar month and count only settled money",
  },
  {
    n: 239,
    group: "N",
    holds: "F9.9",
    text: "Rented numbers that are not earning are listed",
  },
  {
    n: 240,
    group: "N",
    holds: "F9.11",
    text: "The outcome definitions match the ones the business sees",
  },
  {
    n: 241,
    group: "N",
    holds: "F9.12",
    text: "Each needs-attention condition appears when its trigger is met",
  },
  {
    n: 242,
    group: "N",
    holds: "F9.12",
    text: "A business in several conditions is listed once per condition",
  },
  {
    n: 243,
    group: "N",
    holds: "F9.10, F9.13, F10.1c",
    text: "The operator can pause a clock, reset an allowance and set cancelled status",
  },
  {
    n: 244,
    group: "N",
    holds: "F9.7",
    text: "The operator dashboard is nightly with a live median, like the business one",
  },
  // --- O — Multi-tenancy and isolation ----------------------------------
  {
    n: 245,
    group: "O",
    holds: "N1.2",
    text: "A webhook arriving for one business can neither read nor write another's rows",
  },
  {
    n: 246,
    group: "O",
    holds: "N1.1",
    text: "Row-level security blocks a cross-tenant read on the dashboard",
  },
  {
    n: 247,
    group: "O",
    holds: "N1.3",
    text: "Deleting one tenant leaves another's data intact",
  },
  {
    n: 248,
    group: "O",
    holds: "N1.3",
    text: "No data export is offered on any path",
  },
  {
    n: 249,
    group: "O",
    holds: "N2.2",
    text: "Query cost tracks the requesting tenant's size, not the platform's",
  },
  // --- P — Timezone and DST ---------------------------------------------
  {
    n: 250,
    group: "P",
    holds: "N5.1",
    text: "Instants are stored in UTC and rendered in the business's timezone",
  },
  {
    n: 251,
    group: "P",
    holds: "N5.2",
    text: "Day, month and period boundaries are computed in the business's timezone",
  },
  {
    n: 252,
    group: "P",
    holds: "N5.3",
    text: "The hour skipped by spring-forward cannot be booked",
  },
  {
    n: 253,
    group: "P",
    holds: "N5.3",
    text: "The hour duplicated by fall-back resolves unambiguously",
  },
  {
    n: 254,
    group: "P",
    holds: "N5.2",
    text: "Analytics windows bucket correctly across a DST transition",
  },
  {
    n: 255,
    group: "P",
    holds: "N5.2",
    text: "A billing period boundary lands on the right local date across a DST transition",
  },
  // --- Q — Latency and degradation --------------------------------------
  {
    n: 256,
    group: "Q",
    holds: "N3",
    text: "The webhook handler stays within its per-turn budget",
  },
  {
    n: 257,
    group: "Q",
    holds: "N3.1",
    text: "An operation exceeding the hard ceiling is treated as failed",
  },
  {
    n: 258,
    group: "Q",
    holds: "N3.2",
    text: "Work not needed to answer the caller happens after the response",
  },
  {
    n: 259,
    group: "Q",
    holds: "N7.1",
    text: "Stripe being down leaves calls working and usage accruing locally",
  },
  {
    n: 260,
    group: "Q",
    holds: "N7.1",
    text: "Resend being down leaves calls working and email retried",
  },
  {
    n: 261,
    group: "Q",
    holds: "N7.1",
    text: "Places being down degrades onboarding to manual entry",
  },
  {
    n: 262,
    group: "Q",
    holds: "F3.2, N4.2",
    text: "A configuration edit reaches the next caller within 60 seconds",
  },
  {
    n: 263,
    group: "Q",
    holds: "§2.5.5",
    text: "The config cache never holds appointments or busy intervals",
  },
  // --- R — Security and cost control ------------------------------------
  {
    n: 264,
    group: "R",
    holds: "N6.3",
    text: "An unsigned Retell webhook is rejected",
  },
  {
    n: 265,
    group: "R",
    holds: "N6.3",
    text: "An unsigned Stripe webhook is rejected",
  },
  {
    n: 266,
    group: "R",
    holds: "N6.1",
    text: "Provider refresh tokens are encrypted at rest",
  },
  {
    n: 267,
    group: "R",
    holds: "N9.1",
    text: "Enrichment is rate-limited per IP",
  },
  {
    n: 268,
    group: "R",
    holds: "N9.1",
    text: "Passing the daily spend ceiling degrades enrichment to manual entry",
  },
  {
    n: 269,
    group: "R",
    holds: "N9.3",
    text: "Nothing chargeable to Ringly happens before Google sign-in",
  },
];
