import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Generated by `jest --coverage`; gitignored, and its vendored report
    // scripts emit warnings nobody can act on.
    "coverage/**",
  ]),
  {
    // Repo-wide, as the conventional meaning of a leading underscore:
    // "declared on purpose, unused on purpose". Applies everywhere rather than
    // just to tests, because the convention is not a test concern — though
    // tests/behaviour/harness is what makes it load-bearing, since a parameter
    // there documents the signature of a method whose body does not exist yet
    // (EDD §2.20.2), and warnings nobody can act on are how real ones get
    // missed.
    //
    // Caught errors are deliberately *not* exempt: a swallowed error should
    // stay noisy.
    rules: {
      "@typescript-eslint/no-unused-vars": [
        "warn",
        { argsIgnorePattern: "^_", varsIgnorePattern: "^_" },
      ],
    },
  },
]);

export default eslintConfig;
